version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
    container_name: 'rabbitmq'
    restart: unless-stopped
    environment:
       - RABBITMQ_DEFAULT_USER=guest
       - RABBITMQ_DEFAULT_PASS=guest
    ports:
       - 5672:5672
       - 15672:15672
